export type EpostaDili = "tr" | "en" | "de" | "es" | "fr" | "it" | "ar" | "ru";

type SabitMetinler = {
  tarihSaatEtiketi: string;
  kisiSayisiEtiketi: string;
  planlarDegistiMi: string;
  tarihiDegistir: string;
  rezervasyonuIptalEt: string;
  gelemeyecekMisiniz: string;
  afiyetOlsun: string;
  gorusmekUzere: string;
  onayNot: string;

  onayKonu: (restoranAd: string) => string;
  onayBaslik: string;
  onayP1: (restoranAd: string) => string;

  retKonu: (restoranAd: string) => string;
  retBaslik: string;
  retP1: (restoranAd: string, tarihSaat: string) => string;
  retP2: string;

  hatirlatmaKonu: (restoranAd: string) => string;
  hatirlatmaUstEtiket: string;
  hatirlatmaBaslik: string;
  hatirlatmaP1: (restoranAd: string) => string;

  misafirIptalKonu: (restoranAd: string) => string;
  misafirIptalBaslik: string;
  misafirIptalP1: (restoranAd: string, tarihSaat: string) => string;

  restoranIptalKonu: (restoranAd: string) => string;
  restoranIptalBaslik: string;
  restoranIptalP1: (restoranAd: string, tarihSaat: string) => string;
  restoranIptalP2: string;

  yorumKonu: (restoranAd: string) => string;
  yorumBaslik: string;
  yorumP1: (restoranAd: string) => string;
  yorumButon: string;
};

export const EPOSTA_CEVIRILERI: Record<EpostaDili, SabitMetinler> = {
  tr: {
    tarihSaatEtiketi: "Tarih/Saat",
    kisiSayisiEtiketi: "Kişi Sayısı",
    planlarDegistiMi: "Planların değişti mi?",
    tarihiDegistir: "Tarihi değiştir",
    rezervasyonuIptalEt: "Rezervasyonu iptal et",
    gelemeyecekMisiniz: "Gelemeyecek misiniz?",
    afiyetOlsun: "Afiyet olsun!",
    gorusmekUzere: "Görüşmek üzere!",
    onayNot: "Sizi ağırlamaktan mutluluk duyacaklar.",
    onayKonu: (ad) => `Rezervasyonunuz onaylandı — ${ad}`,
    onayBaslik: "Rezervasyonunuz onaylandı",
    onayP1: (ad) => `<strong>${ad}</strong> rezervasyon talebinizi onayladı.`,
    retKonu: (ad) => `Rezervasyon talebiniz için güncelleme — ${ad}`,
    retBaslik: "Talebiniz bu saat için onaylanamadı",
    retP1: (ad, t) => `<strong>${ad}</strong>, ${t} için talebinizi bu sefer onaylayamadı.`,
    retP2: "Farklı bir tarih/saat seçerek tekrar deneyebilirsiniz.",
    hatirlatmaKonu: (ad) => `Hatırlatma: Bugün ${ad}'da yer ayırttınız`,
    hatirlatmaUstEtiket: "Masadaki'den otomatik hatırlatma",
    hatirlatmaBaslik: "Rezervasyonunuz yaklaşıyor",
    hatirlatmaP1: (ad) => `<strong>${ad}</strong>'da yeriniz hazır olacak.`,
    misafirIptalKonu: (ad) => `Rezervasyonunuz iptal edildi — ${ad}`,
    misafirIptalBaslik: "Rezervasyonunuz iptal edildi",
    misafirIptalP1: (ad, t) =>
      `<strong>${ad}</strong> için ${t} tarihli rezervasyonunuzu iptal ettiniz.`,
    restoranIptalKonu: (ad) => `Rezervasyonunuz iptal edildi — ${ad}`,
    restoranIptalBaslik: "Rezervasyonunuz iptal edildi",
    restoranIptalP1: (ad, t) => `<strong>${ad}</strong>, ${t} tarihli rezervasyonunuzu iptal etti.`,
    restoranIptalP2: "Sorularınız için doğrudan restoranla iletişime geçebilirsiniz.",
    yorumKonu: (ad) => `${ad} deneyiminizi puanlayın`,
    yorumBaslik: "Nasıl geçti?",
    yorumP1: (ad) => `<strong>${ad}</strong>'daki deneyiminizi diğer misafirlerle paylaşmak ister misiniz?`,
    yorumButon: "Yorum bırak",
  },
  en: {
    tarihSaatEtiketi: "Date/Time",
    kisiSayisiEtiketi: "Party Size",
    planlarDegistiMi: "Plans changed?",
    tarihiDegistir: "Change the date",
    rezervasyonuIptalEt: "Cancel reservation",
    gelemeyecekMisiniz: "Can't make it?",
    afiyetOlsun: "Enjoy your meal!",
    gorusmekUzere: "See you soon!",
    onayNot: "They'll be happy to have you.",
    onayKonu: (ad) => `Your reservation is confirmed — ${ad}`,
    onayBaslik: "Your reservation is confirmed",
    onayP1: (ad) => `<strong>${ad}</strong> confirmed your reservation request.`,
    retKonu: (ad) => `Update on your reservation request — ${ad}`,
    retBaslik: "Your request couldn't be approved for this time",
    retP1: (ad, t) => `<strong>${ad}</strong> couldn't approve your request for ${t} this time.`,
    retP2: "You can try again with a different date/time.",
    hatirlatmaKonu: (ad) => `Reminder: you have a reservation at ${ad} today`,
    hatirlatmaUstEtiket: "Automatic reminder from Masadaki",
    hatirlatmaBaslik: "Your reservation is coming up",
    hatirlatmaP1: (ad) => `Your table at <strong>${ad}</strong> will be ready.`,
    misafirIptalKonu: (ad) => `Your reservation was cancelled — ${ad}`,
    misafirIptalBaslik: "Your reservation was cancelled",
    misafirIptalP1: (ad, t) => `You cancelled your ${t} reservation at <strong>${ad}</strong>.`,
    restoranIptalKonu: (ad) => `Your reservation was cancelled — ${ad}`,
    restoranIptalBaslik: "Your reservation was cancelled",
    restoranIptalP1: (ad, t) => `<strong>${ad}</strong> cancelled your reservation for ${t}.`,
    restoranIptalP2: "Feel free to contact the restaurant directly with any questions.",
    yorumKonu: (ad) => `Rate your experience at ${ad}`,
    yorumBaslik: "How was it?",
    yorumP1: (ad) => `Would you like to share your experience at <strong>${ad}</strong> with other guests?`,
    yorumButon: "Leave a review",
  },
  de: {
    tarihSaatEtiketi: "Datum/Uhrzeit",
    kisiSayisiEtiketi: "Personenzahl",
    planlarDegistiMi: "Pläne geändert?",
    tarihiDegistir: "Termin ändern",
    rezervasyonuIptalEt: "Reservierung stornieren",
    gelemeyecekMisiniz: "Können Sie nicht kommen?",
    afiyetOlsun: "Guten Appetit!",
    gorusmekUzere: "Bis bald!",
    onayNot: "Man freut sich auf Ihren Besuch.",
    onayKonu: (ad) => `Ihre Reservierung ist bestätigt — ${ad}`,
    onayBaslik: "Ihre Reservierung ist bestätigt",
    onayP1: (ad) => `<strong>${ad}</strong> hat Ihre Reservierungsanfrage bestätigt.`,
    retKonu: (ad) => `Neuigkeiten zu Ihrer Reservierungsanfrage — ${ad}`,
    retBaslik: "Ihre Anfrage konnte für diese Zeit nicht bestätigt werden",
    retP1: (ad, t) => `<strong>${ad}</strong> konnte Ihre Anfrage für ${t} diesmal nicht bestätigen.`,
    retP2: "Sie können es mit einem anderen Datum/einer anderen Uhrzeit erneut versuchen.",
    hatirlatmaKonu: (ad) => `Erinnerung: Sie haben heute eine Reservierung bei ${ad}`,
    hatirlatmaUstEtiket: "Automatische Erinnerung von Masadaki",
    hatirlatmaBaslik: "Ihre Reservierung steht bevor",
    hatirlatmaP1: (ad) => `Ihr Tisch bei <strong>${ad}</strong> wird bereitstehen.`,
    misafirIptalKonu: (ad) => `Ihre Reservierung wurde storniert — ${ad}`,
    misafirIptalBaslik: "Ihre Reservierung wurde storniert",
    misafirIptalP1: (ad, t) => `Sie haben Ihre Reservierung bei <strong>${ad}</strong> für ${t} storniert.`,
    restoranIptalKonu: (ad) => `Ihre Reservierung wurde storniert — ${ad}`,
    restoranIptalBaslik: "Ihre Reservierung wurde storniert",
    restoranIptalP1: (ad, t) => `<strong>${ad}</strong> hat Ihre Reservierung für ${t} storniert.`,
    restoranIptalP2: "Bei Fragen können Sie sich gerne direkt an das Restaurant wenden.",
    yorumKonu: (ad) => `Bewerten Sie Ihren Besuch bei ${ad}`,
    yorumBaslik: "Wie war's?",
    yorumP1: (ad) => `Möchten Sie Ihre Erfahrung bei <strong>${ad}</strong> mit anderen Gästen teilen?`,
    yorumButon: "Bewertung abgeben",
  },
  es: {
    tarihSaatEtiketi: "Fecha/Hora",
    kisiSayisiEtiketi: "Número de personas",
    planlarDegistiMi: "¿Cambiaron tus planes?",
    tarihiDegistir: "Cambiar la fecha",
    rezervasyonuIptalEt: "Cancelar reserva",
    gelemeyecekMisiniz: "¿No podrás venir?",
    afiyetOlsun: "¡Buen provecho!",
    gorusmekUzere: "¡Hasta pronto!",
    onayNot: "Estarán encantados de recibirte.",
    onayKonu: (ad) => `Tu reserva ha sido confirmada — ${ad}`,
    onayBaslik: "Tu reserva ha sido confirmada",
    onayP1: (ad) => `<strong>${ad}</strong> confirmó tu solicitud de reserva.`,
    retKonu: (ad) => `Actualización sobre tu solicitud de reserva — ${ad}`,
    retBaslik: "Tu solicitud no pudo confirmarse para este horario",
    retP1: (ad, t) => `<strong>${ad}</strong> no pudo confirmar tu solicitud para ${t} esta vez.`,
    retP2: "Puedes intentarlo de nuevo con otra fecha u hora.",
    hatirlatmaKonu: (ad) => `Recordatorio: hoy tienes una reserva en ${ad}`,
    hatirlatmaUstEtiket: "Recordatorio automático de Masadaki",
    hatirlatmaBaslik: "Tu reserva se acerca",
    hatirlatmaP1: (ad) => `Tu mesa en <strong>${ad}</strong> estará lista.`,
    misafirIptalKonu: (ad) => `Tu reserva fue cancelada — ${ad}`,
    misafirIptalBaslik: "Tu reserva fue cancelada",
    misafirIptalP1: (ad, t) => `Cancelaste tu reserva del ${t} en <strong>${ad}</strong>.`,
    restoranIptalKonu: (ad) => `Tu reserva fue cancelada — ${ad}`,
    restoranIptalBaslik: "Tu reserva fue cancelada",
    restoranIptalP1: (ad, t) => `<strong>${ad}</strong> canceló tu reserva del ${t}.`,
    restoranIptalP2: "Si tienes preguntas, puedes contactar directamente al restaurante.",
    yorumKonu: (ad) => `Califica tu experiencia en ${ad}`,
    yorumBaslik: "¿Qué tal fue?",
    yorumP1: (ad) => `¿Quieres compartir tu experiencia en <strong>${ad}</strong> con otros huéspedes?`,
    yorumButon: "Dejar una reseña",
  },
  fr: {
    tarihSaatEtiketi: "Date/Heure",
    kisiSayisiEtiketi: "Nombre de personnes",
    planlarDegistiMi: "Vos plans ont changé ?",
    tarihiDegistir: "Changer la date",
    rezervasyonuIptalEt: "Annuler la réservation",
    gelemeyecekMisiniz: "Vous ne pourrez pas venir ?",
    afiyetOlsun: "Bon appétit !",
    gorusmekUzere: "À bientôt !",
    onayNot: "Ils seront ravis de vous accueillir.",
    onayKonu: (ad) => `Votre réservation est confirmée — ${ad}`,
    onayBaslik: "Votre réservation est confirmée",
    onayP1: (ad) => `<strong>${ad}</strong> a confirmé votre demande de réservation.`,
    retKonu: (ad) => `Mise à jour de votre demande de réservation — ${ad}`,
    retBaslik: "Votre demande n'a pas pu être confirmée pour cet horaire",
    retP1: (ad, t) => `<strong>${ad}</strong> n'a pas pu confirmer votre demande pour ${t} cette fois.`,
    retP2: "Vous pouvez réessayer avec une autre date/heure.",
    hatirlatmaKonu: (ad) => `Rappel : vous avez une réservation aujourd'hui chez ${ad}`,
    hatirlatmaUstEtiket: "Rappel automatique de Masadaki",
    hatirlatmaBaslik: "Votre réservation approche",
    hatirlatmaP1: (ad) => `Votre table chez <strong>${ad}</strong> sera prête.`,
    misafirIptalKonu: (ad) => `Votre réservation a été annulée — ${ad}`,
    misafirIptalBaslik: "Votre réservation a été annulée",
    misafirIptalP1: (ad, t) => `Vous avez annulé votre réservation du ${t} chez <strong>${ad}</strong>.`,
    restoranIptalKonu: (ad) => `Votre réservation a été annulée — ${ad}`,
    restoranIptalBaslik: "Votre réservation a été annulée",
    restoranIptalP1: (ad, t) => `<strong>${ad}</strong> a annulé votre réservation du ${t}.`,
    restoranIptalP2: "Pour toute question, contactez directement le restaurant.",
    yorumKonu: (ad) => `Évaluez votre expérience chez ${ad}`,
    yorumBaslik: "Comment ça s'est passé ?",
    yorumP1: (ad) => `Souhaitez-vous partager votre expérience chez <strong>${ad}</strong> avec d'autres clients ?`,
    yorumButon: "Laisser un avis",
  },
  it: {
    tarihSaatEtiketi: "Data/Ora",
    kisiSayisiEtiketi: "Numero di persone",
    planlarDegistiMi: "I tuoi piani sono cambiati?",
    tarihiDegistir: "Cambia la data",
    rezervasyonuIptalEt: "Annulla la prenotazione",
    gelemeyecekMisiniz: "Non potrai venire?",
    afiyetOlsun: "Buon appetito!",
    gorusmekUzere: "A presto!",
    onayNot: "Saranno felici di accoglierti.",
    onayKonu: (ad) => `La tua prenotazione è confermata — ${ad}`,
    onayBaslik: "La tua prenotazione è confermata",
    onayP1: (ad) => `<strong>${ad}</strong> ha confermato la tua richiesta di prenotazione.`,
    retKonu: (ad) => `Aggiornamento sulla tua richiesta di prenotazione — ${ad}`,
    retBaslik: "La tua richiesta non è stata confermata per questo orario",
    retP1: (ad, t) => `<strong>${ad}</strong> non ha potuto confermare la tua richiesta per ${t} questa volta.`,
    retP2: "Puoi riprovare con una data/ora diversa.",
    hatirlatmaKonu: (ad) => `Promemoria: oggi hai una prenotazione da ${ad}`,
    hatirlatmaUstEtiket: "Promemoria automatico da Masadaki",
    hatirlatmaBaslik: "La tua prenotazione si avvicina",
    hatirlatmaP1: (ad) => `Il tuo tavolo da <strong>${ad}</strong> sarà pronto.`,
    misafirIptalKonu: (ad) => `La tua prenotazione è stata annullata — ${ad}`,
    misafirIptalBaslik: "La tua prenotazione è stata annullata",
    misafirIptalP1: (ad, t) => `Hai annullato la tua prenotazione del ${t} da <strong>${ad}</strong>.`,
    restoranIptalKonu: (ad) => `La tua prenotazione è stata annullata — ${ad}`,
    restoranIptalBaslik: "La tua prenotazione è stata annullata",
    restoranIptalP1: (ad, t) => `<strong>${ad}</strong> ha annullato la tua prenotazione del ${t}.`,
    restoranIptalP2: "Per qualsiasi domanda, puoi contattare direttamente il ristorante.",
    yorumKonu: (ad) => `Valuta la tua esperienza da ${ad}`,
    yorumBaslik: "Com'è andata?",
    yorumP1: (ad) => `Vuoi condividere la tua esperienza da <strong>${ad}</strong> con altri ospiti?`,
    yorumButon: "Lascia una recensione",
  },
  ar: {
    tarihSaatEtiketi: "التاريخ/الوقت",
    kisiSayisiEtiketi: "عدد الأشخاص",
    planlarDegistiMi: "هل تغيّرت خططك؟",
    tarihiDegistir: "تغيير الموعد",
    rezervasyonuIptalEt: "إلغاء الحجز",
    gelemeyecekMisiniz: "لن تتمكن من الحضور؟",
    afiyetOlsun: "بالهناء والشفاء!",
    gorusmekUzere: "إلى اللقاء قريباً!",
    onayNot: "سيكونون سعداء باستقبالك.",
    onayKonu: (ad) => `تم تأكيد حجزك — ${ad}`,
    onayBaslik: "تم تأكيد حجزك",
    onayP1: (ad) => `أكّد <strong>${ad}</strong> طلب حجزك.`,
    retKonu: (ad) => `تحديث بخصوص طلب حجزك — ${ad}`,
    retBaslik: "تعذّر تأكيد طلبك لهذا الموعد",
    retP1: (ad, t) => `لم يتمكن <strong>${ad}</strong> من تأكيد طلبك لموعد ${t} هذه المرة.`,
    retP2: "يمكنك المحاولة مرة أخرى بتاريخ أو وقت مختلف.",
    hatirlatmaKonu: (ad) => `تذكير: لديك حجز اليوم في ${ad}`,
    hatirlatmaUstEtiket: "تذكير تلقائي من Masadaki",
    hatirlatmaBaslik: "موعد حجزك يقترب",
    hatirlatmaP1: (ad) => `طاولتك في <strong>${ad}</strong> ستكون جاهزة.`,
    misafirIptalKonu: (ad) => `تم إلغاء حجزك — ${ad}`,
    misafirIptalBaslik: "تم إلغاء حجزك",
    misafirIptalP1: (ad, t) => `لقد ألغيت حجزك بتاريخ ${t} في <strong>${ad}</strong>.`,
    restoranIptalKonu: (ad) => `تم إلغاء حجزك — ${ad}`,
    restoranIptalBaslik: "تم إلغاء حجزك",
    restoranIptalP1: (ad, t) => `ألغى <strong>${ad}</strong> حجزك بتاريخ ${t}.`,
    restoranIptalP2: "لأي استفسار، يمكنك التواصل مباشرة مع المطعم.",
    yorumKonu: (ad) => `قيّم تجربتك في ${ad}`,
    yorumBaslik: "كيف كانت تجربتك؟",
    yorumP1: (ad) => `هل ترغب بمشاركة تجربتك في <strong>${ad}</strong> مع ضيوف آخرين؟`,
    yorumButon: "اكتب تقييماً",
  },
  ru: {
    tarihSaatEtiketi: "Дата/Время",
    kisiSayisiEtiketi: "Количество гостей",
    planlarDegistiMi: "Планы изменились?",
    tarihiDegistir: "Изменить дату",
    rezervasyonuIptalEt: "Отменить бронь",
    gelemeyecekMisiniz: "Не сможете прийти?",
    afiyetOlsun: "Приятного аппетита!",
    gorusmekUzere: "До скорой встречи!",
    onayNot: "Там будут рады вас видеть.",
    onayKonu: (ad) => `Ваша бронь подтверждена — ${ad}`,
    onayBaslik: "Ваша бронь подтверждена",
    onayP1: (ad) => `<strong>${ad}</strong> подтвердил ваш запрос на бронирование.`,
    retKonu: (ad) => `Обновление по вашему запросу на бронирование — ${ad}`,
    retBaslik: "Ваш запрос не удалось подтвердить на это время",
    retP1: (ad, t) => `<strong>${ad}</strong> не смог подтвердить ваш запрос на ${t} в этот раз.`,
    retP2: "Вы можете попробовать снова с другой датой/временем.",
    hatirlatmaKonu: (ad) => `Напоминание: сегодня у вас бронь в ${ad}`,
    hatirlatmaUstEtiket: "Автоматическое напоминание от Masadaki",
    hatirlatmaBaslik: "Скоро ваша бронь",
    hatirlatmaP1: (ad) => `Ваш столик в <strong>${ad}</strong> будет готов.`,
    misafirIptalKonu: (ad) => `Ваша бронь отменена — ${ad}`,
    misafirIptalBaslik: "Ваша бронь отменена",
    misafirIptalP1: (ad, t) => `Вы отменили бронь на ${t} в <strong>${ad}</strong>.`,
    restoranIptalKonu: (ad) => `Ваша бронь отменена — ${ad}`,
    restoranIptalBaslik: "Ваша бронь отменена",
    restoranIptalP1: (ad, t) => `<strong>${ad}</strong> отменил вашу бронь на ${t}.`,
    restoranIptalP2: "По любым вопросам вы можете связаться с рестораном напрямую.",
    yorumKonu: (ad) => `Оцените свой опыт в ${ad}`,
    yorumBaslik: "Как всё прошло?",
    yorumP1: (ad) => `Хотите поделиться впечатлениями о <strong>${ad}</strong> с другими гостями?`,
    yorumButon: "Оставить отзыв",
  },
};

export const EPOSTA_LOCALE_MAP: Record<EpostaDili, string> = {
  tr: "tr-TR",
  en: "en-US",
  de: "de-DE",
  es: "es-ES",
  fr: "fr-FR",
  it: "it-IT",
  ar: "ar-SA",
  ru: "ru-RU",
};

export function epostaDiliCoz(dil: string | null | undefined): EpostaDili {
  const bilinenler: EpostaDili[] = ["tr", "en", "de", "es", "fr", "it", "ar", "ru"];
  return bilinenler.includes(dil as EpostaDili) ? (dil as EpostaDili) : "tr";
}
